spring.application.name=sky_telegram2
spring.datasource.url=jdbc:postgresql://localhost:5432/sky_telegram_211423022026
spring.datasource.username=postgres
spring.datasource.password=postgres
telegram.bot.token=6915026805:AAGSyEmbkz-kGduQVDcz2lgmXDF-yK3SvPY